apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: training-from-scratch-
spec:
  serviceAccountName: argo-workflow
  imagePullSecrets:
  - name: incisive-azurecrio-secret
  ttlStrategy:
    secondsAfterCompletion: 100
    secondsAfterSuccess: 100
    secondsAfterFailure: 1200
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  entrypoint: main
  onExit: exit-handler
  volumes:
  - name: ai-elements
    emptyDir: {}
  - name: output-elements
    emptyDir: {}
  - name: raw-platform-vars
    configMap:
      name: ai-engine-config-2nd-prototype
  - name: platform-vars
    emptyDir: {}
      
  templates:
  - name: main
    nodeSelector: {dataPartner: "{{inputs.parameters.execution_dataPartner}}"}
    retryStrategy:
      limit: "2"
      retryPolicy: "Always"
    inputs:
      parameters:
      - name: platform_maasApiHostname
      - name: platform_orchestratorApiHostname
      - name: platform_processorResourceManagerVersion
      - name: platform_processorResourceManagerCallbackUrl
      - name: aiEngine_plaformVarsInputDataTrainingTabular
      - name: aiEngine_plaformVarsInputDataTrainingImagery
      - name: aiEngine_plaformVarsInputAIElements
      - name: aiEngine_plaformVarsInputUserVars
      - name: aiEngine_plaformVarsOutputElements
      - name: aiEngine_plaformVarsOutputModel
      - name: aiEngine_plaformVarsOutputEvaluationMetrics
      - name: aiEngine_plaformVarsApiPingUrl
      - name: aiEngine_plaformVarsApiRunUrl
      - name: aiEngine_plaformVarsApiEndUrl
      - name: execution_id
      - name: execution_dataPartner
      - name: execution_dataPartnerDataPath
      - name: execution_dataPartnerPatients
      - name: execution_main-ai-engine-version
      - name: execution_main-ai-engine-container-name
      - name: execution_main-ai-engine-container-version
      - name: execution_main-ai-engine-prm-api-host
      - name: execution_main-ai-engine-plaform-vars-api-host
      - name: execution_outputAIModelName
      - name: execution_outputAIModelDescription
      - name: execution_outputAIModelMergeType
    outputs:
      parameters:
      - name: error-message
        valueFrom:
          default: "Unexpected error"
          path: /usr/application/error_message.txt
        globalName: main-error-message
    initContainers:
    - name: config-changer
      image: "incisive.azurecr.io/processor-resource-manager:{{inputs.parameters.platform_processorResourceManagerVersion}}"
      args: ["{\"actions\":[{\"name\":\"change_api_host_and_port\",\"read_file_path\":\"/platform_vars.json\",\"write_file_path\":\"/tmp/config_changer/platform_vars.json\",\"api_host_and_port\":\"{{inputs.parameters.execution_main-ai-engine-plaform-vars-api-host}}\"},{\"name\":\"add_data_provider_info\",\"read_file_path\":\"/tmp/config_changer/platform_vars.json\",\"write_file_path\":\"/tmp/config_changer/platform_vars.json\",\"data_provider\":\"{{inputs.parameters.execution_dataPartner}}\"},]}"]
      volumeMounts:
      - name: raw-platform-vars
        mountPath: /platform_vars.json
        subPath: platform_vars.json  
      - name: platform-vars
        mountPath: /tmp/config_changer
    volumes:
    - name: internal-data-tabular
      emptyDir: {}
    - name: internal-data-imagery
      hostPath:
        path: "{{inputs.parameters.execution_dataPartnerDataPath}}"
        type: Directory
    containerSet:
      volumeMounts:
      - name: internal-data-tabular
        mountPath: "{{inputs.parameters.aiEngine_plaformVarsInputDataTrainingTabular}}"
      - name: internal-data-imagery
        mountPath: "{{inputs.parameters.aiEngine_plaformVarsInputDataTrainingImagery}}"
        readOnly: true
      - name: ai-elements
        mountPath: "{{inputs.parameters.aiEngine_plaformVarsInputAIElements}}"
      - name: output-elements
        mountPath: "{{inputs.parameters.aiEngine_plaformVarsOutputElements}}"
      - name: platform-vars
        mountPath: /platform_vars.json
        subPath: platform_vars.json
      containers:
        - name: main
          image: "incisive.azurecr.io/processor-resource-manager:{{inputs.parameters.platform_processorResourceManagerVersion}}"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          args: ["{\"actions\":[{\"name\":\"update_to_running\",\"update_status_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_running/\"},{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}\"},{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsOutputElements}}\"},{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsOutputModel}}\"},{\"name\":\"download_user_vars\",\"user_vars_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/download_user_vars/?descriptor=main-ai-engine\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputUserVars}}\"},{\"name\":\"prepare_internal_data\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputDataTrainingTabular}}\",\"information_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/retrieve_data_partner_information/?data_partner={{inputs.parameters.execution_dataPartner}}\"},{\"name\":\"run_ai_engine\",\"use_case\":\"training_from_scratch\",\"max_iteration_time\":1200,\"max_initialization_time\":600,\"client_host\":\"{{workflow.parameters.execution_main-ai-engine-plaform-vars-api-host}}\",\"server_host\":\"{{workflow.parameters.execution_main-ai-engine-prm-api-host}}\",\"ping_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiPingUrl}}\",\"run_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiRunUrl}}\",\"callback_url\":\"{{workflow.parameters.platform_processorResourceManagerCallbackUrl}}\"},{\"name\":\"end_ai_engine\",\"max_finalization_time\":30,\"max_finalization_retries\":4,\"client_host\":\"{{workflow.parameters.execution_main-ai-engine-plaform-vars-api-host}}\",\"ping_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiPingUrl}}\",\"end_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiEndUrl}}\"},{\"name\":\"update_to_succeeded\",\"update_status_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_succeeded/\",\"upload_ai_model\":true,\"upload_evaluation_metrics\":true,\"upload_generic_file\":false,\"ai_model_upload_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/ai_models/update_or_create/\",\"ai_model_delete_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/ai_models/\",\"ai_model_upload_path\":\"{{workflow.parameters.aiEngine_plaformVarsOutputModel}}/*\",\"ai_model_user_vars_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputUserVars}}\",\"ai_model_upload_metadata\":{\"ai_engine_version\":{{workflow.parameters.execution_main-ai-engine-version}},\"name\":\"{{workflow.parameters.execution_outputAIModelName}}\",\"data_partners_patients\":{{workflow.parameters.execution_dataPartnerPatients}},\"description\":\"{{workflow.parameters.execution_outputAIModelDescription}}\",\"merge_type\":\"{{workflow.parameters.execution_outputAIModelMergeType}}\"},\"evaluation_metrics_upload_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/evaluation_metrics/update_or_create/\",\"evaluation_metrics_delete_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/evaluation_metrics/\",\"evaluation_metrics_upload_path\":\"{{workflow.parameters.aiEngine_plaformVarsOutputEvaluationMetrics}}\",\"evaluation_metrics_upload_metadata\":{\"data_partners_patients\":{{workflow.parameters.execution_dataPartnerPatients}}}}]}", "--failure-actions", "{\"actions\":[{\"name\":\"ping_ai_engine\",\"max_initialization_time\":30,\"client_host\":\"{{workflow.parameters.execution_main-ai-engine-plaform-vars-api-host}}\",\"ping_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiPingUrl}}\"},{\"name\":\"end_ai_engine\",\"max_finalization_time\":30,\"max_finalization_retries\":4,\"client_host\":\"{{workflow.parameters.execution_main-ai-engine-plaform-vars-api-host}}\",\"ping_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiPingUrl}}\",\"end_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiEndUrl}}\"}]}"]
        - name: main-ai-engine
          image: "incisive.azurecr.io/{{inputs.parameters.execution_main-ai-engine-container-name}}:{{inputs.parameters.execution_main-ai-engine-container-version}}"
          resources:
            requests:
              cpu: 250m
              memory: 2560Mi
            limits:
              cpu: 2000m
              memory: 2560Mi
        
  - name: exit-handler
    steps:
    - - name: notify-failure
        when: "{{workflow.status}} != Succeeded"
        template: exit-handler-communicate-error

  - name: exit-handler-communicate-error
    inputs:
      parameters:
      - name: error-message
        value: "{{workflow.outputs.parameters.main-error-message}}"
    nodeSelector: {"{{workflow.parameters.platform_centralNodeLabelKey}}": "{{workflow.parameters.platform_centralNodeLabelValue}}"}
    container:
      image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
      args: ["{\"actions\":[{\"name\":\"update_to_failed\", \"message\":\"{{inputs.parameters.error-message}}\", \"update_status_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_failed/\"}]}"]
