# Generated by Django 3.2.9 on 2022-03-21 08:19

from django.db import migrations, models

import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('main.jobtraining', 'job training'), ('main.jobwithpretrainedmodel', 'job with pretrained model'), ('main.jobtrainingfromscratch', 'job training from scratch'), ('main.jobtrainingfrompretrainedmodel', 'job training from pretrained model'), ('main.jobevaluatingfrompretrainedmodel', 'job evaluating from pretrained model'), ('main.jobinferencingfrompretrainedmodel', 'job inferencing from pretrained model')], db_index=True, max_length=255)),
                ('random_id', models.CharField(default=main.models.random_string, max_length=100)),
                ('data_partners_patients', models.TextField(null=True)),
                ('data_path', models.CharField(max_length=100, null=True)),
                ('number_iterations', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('result', models.CharField(max_length=100, null=True)),
                ('use_case', models.CharField(choices=[('training_from_scratch', 'Training From Scratch'), ('training_from_pretrained_model', 'Training From Pretrained Model'), ('evaluating_from_pretrained_model', 'Evaluating From Pretrained Model'), ('inferencing_from_pretrained_model', 'Inferencing From Pretrained Model')], max_length=33)),
                ('ai_engine_config', models.FileField(upload_to='ai_engine_configs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=200, null=True)),
                ('model_type', models.CharField(max_length=50, null=True)),
                ('model_description', models.CharField(max_length=500, null=True)),
                ('model_id', models.IntegerField(null=True)),
                ('ai_engine_id', models.IntegerField(null=True)),
                ('input_data_files', models.FileField(null=True, upload_to='inference_input_data_files')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobTraining',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.job',),
        ),
        migrations.CreateModel(
            name='JobWithPretrainedModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.job',),
        ),
        migrations.CreateModel(
            name='JobEvaluatingFromPretrainedModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.jobwithpretrainedmodel',),
        ),
        migrations.CreateModel(
            name='JobInferencingFromPretrainedModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.jobwithpretrainedmodel',),
        ),
        migrations.CreateModel(
            name='JobTrainingFromPretrainedModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.jobtraining', 'main.jobwithpretrainedmodel'),
        ),
        migrations.CreateModel(
            name='JobTrainingFromScratch',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.jobtraining',),
        ),
    ]
