# Generated by Django 4.1.7 on 2023-04-14 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionWorkflow',
            fields=[
                ('workflow_name', models.CharField(max_length=200)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.execution')),
            ],
        ),
    ]
