# Generated by Django 4.2.4 on 2023-09-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executioninputaiengine',
            name='max_iteration_time',
            field=models.IntegerField(default=1200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executioninputaimodel',
            name='download_resume_retries',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
