# Generated by Django 4.2.4 on 2023-10-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_executioninputaiengine_max_iteration_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executioninputaiengine',
            name='cpu_limit',
            field=models.CharField(default='4000m', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executioninputaiengine',
            name='cpu_request',
            field=models.CharField(default='250m', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executioninputaiengine',
            name='memory_limit',
            field=models.CharField(default='3584Mi', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executioninputaiengine',
            name='memory_request',
            field=models.CharField(default='3584Mi', max_length=50),
            preserve_default=False,
        ),
    ]
