# Generated by Django 4.2.4 on 2024-02-12 14:29

from django.db import migrations, models
import django.db.models.deletion
import main.models.execution


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_executioninputaiengine_cpu_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionInputReportMetadata',
            fields=[
                ('report_metadata', models.FileField(max_length=300, upload_to=main.models.execution.execution_external_data_report_metadata_path)),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.execution')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaInputReportMetadata',
            fields=[
                ('schema', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.schema')),
            ],
        ),
    ]
