apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: d-4-2-service-breast-cancer-
spec:
  serviceAccountName: argo-workflow
  imagePullSecrets:
  - name: incisive-azurecrio-secret
  ttlStrategy:
    secondsAfterCompletion: 100
    secondsAfterSuccess: 100
    secondsAfterFailure: 1200
  nodeSelector: {agentpool: agentpool}
  entrypoint: d-4-2-service-breast-cancer
  volumes:  # internally shared volumes
  - name: ai-elements-prioritization-and-segmentation
    emptyDir: {}
  - name: ai-elements-birads-classification
    emptyDir: {}
  - name: ai-elements-medical-report-generation
    emptyDir: {}
  - name: raw-platform-vars
    configMap:
      name: ai-engine-config-2nd-prototype
  - name: platform-vars
    emptyDir: {}
  volumeClaimTemplates:  # shared volumes between steps
  - metadata:
      name: input-elements
    spec:
      storageClassName: managed-premium
      accessModes: ["ReadWriteOnce"]  # being Many is not possible, this impossibilitates the parallelism
      resources:
        requests:
          storage: 500Mi
  - metadata:
      name: visualization-prioritization-and-segmentation
    spec:
      storageClassName: managed-premium
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Mi
  - metadata:
      name: visualization-birads-classification
    spec:
      storageClassName: managed-premium
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Mi
  - metadata:
      name: visualization-medical-report-generation
    spec:
      storageClassName: managed-premium
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 50Mi

  templates:
    - name: d-4-2-service-breast-cancer
      inputs:
        parameters:
        - name: platform_maasApiHostname
        - name: platform_orchestratorApiHostname
        - name: platform_processorResourceManagerVersion
        - name: platform_processorResourceManagerCallbackUrl
        - name: platform_processorResourceManagerApiHost
        - name: aiEngine_plaformVarsInputElements
        - name: aiEngine_plaformVarsInputDataInference
        - name: aiEngine_plaformVarsInputAIElements
        - name: aiEngine_plaformVarsInputUserVars
        - name: aiEngine_plaformVarsInputModel
        - name: aiEngine_plaformVarsOutputElements
        - name: aiEngine_plaformVarsOutputInferenceResults
        - name: aiEngine_plaformVarsApiPingUrl
        - name: aiEngine_plaformVarsApiRunUrl
        - name: aiEngine_plaformVarsApiHost
        - name: execution_id
        - name: execution_prioritization-and-segmentation-container-name
        - name: execution_prioritization-and-segmentation-container-version
        - name: execution_prioritization-and-segmentation-ai-model
        - name: execution_prioritization-and-segmentation-plaform-vars-api-host
        - name: execution_birads-classification-container-name
        - name: execution_birads-classification-container-version
        - name: execution_birads-classification-ai-model
        - name: execution_birads-classification-plaform-vars-api-host
        - name: execution_medical-report-generation-container-name
        - name: execution_medical-report-generation-container-version
        - name: execution_medical-report-generation-plaform-vars-api-host
      steps:
      - - name: initialization
          template: initialization-step
      - - name: prioritization-and-segmentation
          template: prioritization-and-segmentation-step
      - - name: birads-classification
          template: birads-classification-step
      - - name: medical-report-generation
          template: medical-report-generation-step
      - - name: finalization
          template: finalization-step

    - name: initialization-step
      container:
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi 
        args: ["{\"actions\":[{\"name\":\"update_to_running\",\"update_status_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_running/\"},{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputDataInference}}\"},{\"name\":\"download_external_data\",\"external_data_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/download_external_data/\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputDataInference}}\"}]}", "--failure-endpoint", "http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_failed/"]
        volumeMounts:
        - name: input-elements
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputElements}}"

    - name: prioritization-and-segmentation-step
      initContainers:
      - name: config-changer
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        args: ["{\"actions\":[{\"name\":\"change_api_host_and_port\",\"read_file_path\":\"/platform_vars.json\",\"write_file_path\":\"/tmp/config_changer/platform_vars.json\",\"api_host_and_port\":\"{{workflow.parameters.execution_prioritization-and-segmentation-plaform-vars-api-host}}\"}]}"]
        volumeMounts:
        - name: raw-platform-vars
          mountPath: /platform_vars.json
          subPath: platform_vars.json  
        - name: platform-vars
          mountPath: /tmp/config_changer
      container:
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 1Gi
        args: ["{\"actions\":[{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}\"},{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputModel}}\"},{\"name\":\"download_user_vars\",\"user_vars_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/download_user_vars/?descriptor=prioritization-and-segmentation\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputUserVars}}\"},{\"name\":\"download_ai_model\",\"ai_model_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/ai_models/{{workflow.parameters.execution_prioritization-and-segmentation-ai-model}}/download_contents/\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputModel}}\"},{\"name\":\"run_ai_engine\",\"use_case\":\"inferencing_from_pretrained_model\",\"max_iteration_time\":1200,\"max_initialization_time\":600,\"client_host\":\"{{workflow.parameters.aiEngine_plaformVarsApiHost}}\",\"server_host\":\"{{workflow.parameters.platform_processorResourceManagerApiHost}}\",\"ping_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiPingUrl}}\",\"run_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiRunUrl}}\",\"callback_url\":\"{{workflow.parameters.platform_processorResourceManagerCallbackUrl}}\"}]}", "--failure-endpoint", "http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_failed/"]
        volumeMounts:
        - name: ai-elements-prioritization-and-segmentation
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}"
      sidecars:
      - name: main-ai-engine
        image: "incisive.azurecr.io/{{workflow.parameters.execution_prioritization-and-segmentation-container-name}}:{{workflow.parameters.execution_prioritization-and-segmentation-container-version}}"
        resources:
          requests:
            cpu: 250m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: input-elements
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputElements}}"
        - name: ai-elements-prioritization-and-segmentation
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}"
          readOnly: true
        - name: visualization-prioritization-and-segmentation
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsOutputInferenceResults}}"
        - name: platform-vars
          mountPath: /platform_vars.json
          subPath: platform_vars.json
        
    - name: birads-classification-step
      initContainers:
      - name: config-changer
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        args: ["{\"actions\":[{\"name\":\"change_api_host_and_port\",\"read_file_path\":\"/platform_vars.json\",\"write_file_path\":\"/tmp/config_changer/platform_vars.json\",\"api_host_and_port\":\"{{workflow.parameters.execution_birads-classification-plaform-vars-api-host}}\"}]}"]
        volumeMounts:
        - name: raw-platform-vars
          mountPath: /platform_vars.json
          subPath: platform_vars.json  
        - name: platform-vars
          mountPath: /tmp/config_changer
      container:
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        resources:
          requests:
            cpu: 250m
            memory: 768Mi
          limits:
            cpu: 1000m
            memory: 768Mi
        args: ["{\"actions\":[{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}\"},{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputModel}}\"},{\"name\":\"download_user_vars\",\"user_vars_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/download_user_vars/?descriptor=birads-classification\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputUserVars}}\"},{\"name\":\"download_ai_model\",\"ai_model_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/ai_models/{{workflow.parameters.execution_birads-classification-ai-model}}/download_contents/\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputModel}}\"},{\"name\":\"run_ai_engine\",\"use_case\":\"inferencing_from_pretrained_model\",\"max_iteration_time\":1200,\"max_initialization_time\":600,\"client_host\":\"{{workflow.parameters.aiEngine_plaformVarsApiHost}}\",\"server_host\":\"{{workflow.parameters.platform_processorResourceManagerApiHost}}\",\"ping_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiPingUrl}}\",\"run_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiRunUrl}}\",\"callback_url\":\"{{workflow.parameters.platform_processorResourceManagerCallbackUrl}}\"}]}", "--failure-endpoint", "http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_failed/"]
        volumeMounts:
        - name: ai-elements-birads-classification
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}"
      sidecars:
      - name: main-ai-engine
        image: "incisive.azurecr.io/{{workflow.parameters.execution_birads-classification-container-name}}:{{workflow.parameters.execution_birads-classification-container-version}}"
        resources:
          requests:
            cpu: 250m
            memory: 2560Mi
          limits:
            cpu: 2000m
            memory: 2560Mi
        volumeMounts:
        - name: input-elements
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputElements}}"
        - name: ai-elements-birads-classification
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}"
          readOnly: true
        - name: visualization-birads-classification
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsOutputInferenceResults}}"
        - name: platform-vars
          mountPath: /platform_vars.json
          subPath: platform_vars.json
        
    - name: medical-report-generation-step
      initContainers:
      - name: config-changer
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        args: ["{\"actions\":[{\"name\":\"change_api_host_and_port\",\"read_file_path\":\"/platform_vars.json\",\"write_file_path\":\"/tmp/config_changer/platform_vars.json\",\"api_host_and_port\":\"{{workflow.parameters.execution_medical-report-generation-plaform-vars-api-host}}\"}]}"]
        volumeMounts:
        - name: raw-platform-vars
          mountPath: /platform_vars.json
          subPath: platform_vars.json  
        - name: platform-vars
          mountPath: /tmp/config_changer
      container:
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        resources:
          requests:
            cpu: 250m
            memory: 768Mi
          limits:
            cpu: 1000m
            memory: 768Mi
        args: ["{\"actions\":[{\"name\":\"create_directory\",\"directory_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}\"},{\"name\":\"download_user_vars\",\"user_vars_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/download_user_vars/?descriptor=medical-report-generation\",\"output_path\":\"{{workflow.parameters.aiEngine_plaformVarsInputUserVars}}\"},{\"name\":\"run_ai_engine\",\"use_case\":\"inferencing_from_pretrained_model\",\"max_iteration_time\":1200,\"max_initialization_time\":600,\"client_host\":\"{{workflow.parameters.aiEngine_plaformVarsApiHost}}\",\"server_host\":\"{{workflow.parameters.platform_processorResourceManagerApiHost}}\",\"ping_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiPingUrl}}\",\"run_url\":\"{{workflow.parameters.aiEngine_plaformVarsApiRunUrl}}\",\"callback_url\":\"{{workflow.parameters.platform_processorResourceManagerCallbackUrl}}\"}]}", "--failure-endpoint", "http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_failed/"]
        volumeMounts:
        - name: ai-elements-medical-report-generation
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}"
      sidecars:
      - name: main-ai-engine
        image: "incisive.azurecr.io/{{workflow.parameters.execution_medical-report-generation-container-name}}:{{workflow.parameters.execution_medical-report-generation-container-version}}"
        resources:
          requests:
            cpu: 250m
            memory: 2560Mi
          limits:
            cpu: 2000m
            memory: 2560Mi
        volumeMounts:
        - name: input-elements
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputElements}}"
        - name: ai-elements-medical-report-generation
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsInputAIElements}}"
          readOnly: true
        - name: visualization-medical-report-generation
          mountPath: "{{workflow.parameters.aiEngine_plaformVarsOutputInferenceResults}}"
        - name: platform-vars
          mountPath: /platform_vars.json
          subPath: platform_vars.json
          
    - name: finalization-step
      container:
        image: "incisive.azurecr.io/processor-resource-manager:{{workflow.parameters.platform_processorResourceManagerVersion}}"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 512Mi
        args: ["{\"actions\":[{\"name\":\"update_to_succeeded\",\"update_status_url\":\"http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_succeeded/\",\"upload_ai_model\":false,\"upload_evaluation_metrics\":false,\"upload_generic_file\":true,\"generic_file_upload_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/generic_files/\",\"generic_file_delete_url\":\"http://{{workflow.parameters.platform_maasApiHostname}}/api/generic_files/\",\"generic_file_upload_path\":\"/tmp/output_elements/\",\"generic_file_upload_metadata\":{\"name\":\"InferenceResultsfromExecution{{workflow.parameters.execution_id}}\"}}]}", "--failure-endpoint", "http://{{workflow.parameters.platform_orchestratorApiHostname}}/api/executions/{{workflow.parameters.execution_id}}/update_to_failed/"]
        volumeMounts:
        - name: visualization-prioritization-and-segmentation
          mountPath: "/tmp/output_elements/prioritization-and-segmentation/"
        - name: visualization-birads-classification
          mountPath: "/tmp/output_elements/birads-classification/"
        - name: visualization-medical-report-generation
          mountPath: "/tmp/output_elements/medical-report-generation/"
          
